# Generated by Django 4.1.7 on 2023-10-06 12:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Trader',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
               
            ],
        ),
        migrations.CreateModel(
            name='Trade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('profit_or_loss', models.DecimalField(decimal_places=2, max_digits=10)),
                ('trader', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashb.trader')),
            ],
        ),
    ]
