# Generated by Django 4.1.7 on 2023-10-06 20:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('dashb', '0002_trader_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trader',
            name='name',
        ),
        migrations.AlterField(
            model_name='trade',
            name='trader',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tradinf_user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='trader',
            name='user',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='trade_user', to=settings.AUTH_USER_MODEL),
        ),
    ]
