# Generated by Django 4.1.7 on 2023-10-06 20:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('dashb', '0003_remove_trader_name_alter_trade_trader_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trader',
            name='user',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
