# Generated by Django 4.1.7 on 2023-10-06 20:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('dashb', '0004_alter_trader_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trade',
            name='trader',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trading_user', to=settings.AUTH_USER_MODEL),
        ),
    ]
