# Generated by Django 4.1.7 on 2023-10-06 21:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('dashb', '0007_customeuser_delete_trader_alter_trade_trader'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CustomeUser',
            new_name='User',
        ),
    ]
