# Generated by Django 4.1.7 on 2023-10-07 05:14

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashb', '0011_trader_alter_trade_trader_delete_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='trader',
            name='starting_capital',
            field=models.DecimalField(decimal_places=2, default=Decimal('100.00'), max_digits=10),
        ),
    ]
